export const iconUrls = {
  btc : 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
  eth : 'https://cdn.coinranking.com/rkRKHOuW/eth.svg',
  usdt : 'https://cdn.coinranking.com/mgHqwlCLj/usdt.svg',
  usdc : 'https://cdn.coinranking.com/jkDfsQbY/usdc.svg',
  bnb : 'https://cdn.coinranking.com/BNL_dZ/bnb.svg',
  busd : 'https://cdn.coinranking.com/SJHRfClq/busd.svg',
  ada : 'https://cdn.coinranking.com/ryYnXhW/ada.svg',
  xrp : 'https://cdn.coinranking.com/BoPuTyfX/xrp.svg',
  hex : 'https://cdn.coinranking.com/iseNAm/hex-vector.svg',
  sol : 'https://cdn.coinranking.com/yvUGQex/solana.svg',
  doge : 'https://cdn.coinranking.com/HarXIuOZ/doge.svg',
  dot : 'https://cdn.coinranking.com/RsljYqnbu/polkadot.svg',
  shib : 'https://cdn.coinranking.com/DLfI-tm/shib.png',
  link : 'https://cdn.coinranking.com/NOPtOem/chainlink.svg',
  steth : 'https://cdn.coinranking.com/UJ-dQdgYY/.png',
  matic : 'https://cdn.coinranking.com/HAfrWkx/polygon-matic-rebrand.png',
  trx : 'https://cdn.coinranking.com/behejNqQs/trx.svg',
  dai : 'https://cdn.coinranking.com/mAZ_LwOE/mutli-collateral-dai.svg',
  uni : 'https://cdn.coinranking.com/heSvUgtl/uniswap-v.svg?size=x',
  avax : 'https://cdn.coinranking.com/SCCw-w/avax-avalanche.png',
  wbtc : 'https://cdn.coinranking.com/o-cvCHu/wbtc[].svg',
  okb : 'https://cdn.coinranking.com/xcZdYtXE/okx.png',
  bit : 'https://cdn.coinranking.com/ClFWIpO/bitdao.png',
  leo : 'https://cdn.coinranking.com/EKqYr/leo.svg',
  etc : 'https://cdn.coinranking.com/rJfyor__W/etc.svg',
  ltc : 'https://cdn.coinranking.com/BUvPxmco/ltcnew.svg',
  ftt : 'https://cdn.coinranking.com/WyBm_EzM/ftx-exchange.svg',
  atom : 'https://cdn.coinranking.com/HJzHboruM/atom.svg',
  near : 'https://cdn.coinranking.com/CthdCnl/near.png',
  xmr : 'https://cdn.coinranking.com/Syz-oSd_Z/xmr.svg',
  cro : 'https://cdn.coinranking.com/ojmM/cro.svg',
  wemix : 'https://cdn.coinranking.com/NMQsoO/.png',
  bch : 'https://cdn.coinranking.com/ByziihX/bch.svg',
  xlm : 'https://cdn.coinranking.com/CxKxsp/Stellar_symbol_black_RGB.svg',
  algo : 'https://cdn.coinranking.com/lzbmCkUGB/algo.svg',
  mana : 'https://cdn.coinranking.com/ph_svUzXs/decentraland().svg',
  ldo : 'https://cdn.coinranking.com/WpLFYZZ/.png',
  vet : 'https://cdn.coinranking.com/B_TDuDm/VEN.svg',
  btcb : 'https://cdn.coinranking.com/Swr_SeZio/.png',
  icp : 'https://cdn.coinranking.com/uJ_RVrmC/dfinity-icp.png',
  cel : 'https://cdn.coinranking.com/XPUTeCYD/New-CEL.png',
  mim : 'https://cdn.coinranking.com/oLYNtlaX/mimlogopng.png',
  sand : 'https://cdn.coinranking.com/kd_vwOcnI/sandbox.png',
  cake : 'https://cdn.coinranking.com/aRtgdwbQ/pancakeswap-cake-logo.png',
  xtz : 'https://cdn.coinranking.com/HkLUdilQ/xtz.svg',
  imx : 'https://cdn.coinranking.com/naRGTY_X/.png',
  aave : 'https://cdn.coinranking.com/bpYKqVX/AAVE.png',
  theta : 'https://cdn.coinranking.com/HJHgkLf/theta.svg',
  hbar : 'https://cdn.coinranking.com/dSCnSLilQ/hedera.svg',
  frax : 'https://cdn.coinranking.com/BpVNCX-NM/frax.png',
}

export const uuids = {
  btc : 'QwsogvtvFCd',
  eth : 'razxDUgYGNAdQ',
  usdt : 'HIVsRcGKkPFtW',
  usdc : 'aKzUVeHh_CON',
  bnb : 'WcwrkfNIFUAe',
  busd : 'vSofuiEsY',
  ada : 'qzawljRxBbYu',
  xrp : '-lMnpVlRs-p',
  hex : 'KmufraZgh',
  sol : 'zNZHO_Sjf',
  doge : 'aGCGd_ucF',
  dot : 'WFGom',
  shib : 'xzeBjL',
  link : 'VLqpJwogdhHNb',
  steth : 'VINVMYfu',
  matic : 'uWtk-ILYii',
  trx : 'qUhEFkIatv',
  dai : 'MoTuySvg',
  uni : '_HFVGiW',
  avax : 'dvUjCzDZ',
  wbtc : 'xWXHge-vvFY',
  okb : 'PDKcptVnzJTmN',
  bit : 'NIgQXme',
  leo : 'mqtUpyBxuO',
  etc : 'hnfQfsYfeIGUQ',
  ltc : 'DBx_ksWhV',
  ftt : 'NfeOYfNcl',
  atom : 'Knsels_Ol-Ny',
  near : 'DCrsaMv',
  xmr : 'mVxFX_iJFp',
  cro : 'PHZTpmEb',
  wemix : 'CsQa-Ov',
  bch : 'ZlZpzOJomIo',
  xlm : 'fiaFeCKEmkaZ',
  algo : 'TpHEIShQw-sJ',
  mana : 'tEf-dnwVBXS',
  ldo : 'PebIOD',
  vet : 'FEbSwxooIl',
  btcb : '_jHRBW',
  icp : 'aMNLwaUbY',
  cel : 'rkXwLmIjUDp',
  mim : 'lORNHeWV',
  sand : 'pxtKbGrg',
  cake : 'ncYFcP',
  xtz : 'fsIbGOEJWbzxG',
  imx : 'ZjIvLU',
  ens : 'SbWqqTui-',
  aave : 'ixgUfzmLR',
  theta : 'BIRxNtoYmwK',
  hbar : 'jadTjB',
};

export const exchangeIds = {
  'BCH': 'bch',
  'Aave': 'aave',
  'AAX': 'aax',
  'AAX Futures': 'aax_futures',
  'ABCC': 'abcc',
  'Acala Swap': 'acala_swap',
  'ACDX Futures': 'acdx_futures',
  'Acsi Finance': 'acsi_finance',
  'AEX': 'aex',
  'Agora Swap': 'agora_swap',
  'Algebra finance': 'algebra_finance',
  'Alpha': 'alpha_five',
  'AltcoinTrader': 'altcointrader',
  'AlterDice': 'alterdice',
  'Altmarkets': 'altmarkets',
  'Amaterasu Finance': 'amaterasu',
  'ApeSwap': 'apeswap_bsc',
  'ApeSwap (Polygon)': 'apeswap_polygon',
  'Aprobit': 'aprobit',
  'ArthSwap': 'arthswap',
  'Astroport (Classic)': 'astroport',
  'AuroraSwap': 'auroraswap',
  'AutoShark Finance': 'autoshark_finance',
  'Azbit': 'azbit',
  'BBX': 'bbx',
  'BabySwap': 'babyswap',
  'Baguette': 'baguette',
  'Bakeryswap': 'bakeryswap',
  'Bakkt': 'bakkt',
  'Balanced Network': 'balanced_network',
  'Balancer (v)': 'balancer',
  'Balancer (Arbitrum)': 'balancer_arbitrum',
  'Balancer (Polygon)': 'balancer_polygon',
  'Balancer (v)': 'balancer_v',
  'Bancor (V)': 'bancor',
  'Bancor (V)': 'bancor_v',
  'Baryon Network': 'baryon_network',
  'BaseFEX': 'basefex',
  'Beamswap': 'beamswap',
  'Beaxy': 'beaxy',
  'Beethoven X': 'beethovenx',
  'Benswap': 'benswap_smart_bitcoin_cash',
  'Bgogo': 'bgogo',
  'Bibox': 'bibox',
  'Bibox (Futures)': 'bibox_futures',
  'Biconomy': 'biconomy',
  'BigONE': 'bigone',
  'BigONE Futures': 'bigone_futures',
  'Bilaxy': 'bilaxy',
  'Binance': 'binance',
  'Binance DEX': 'binance_dex',
  'Binance DEX (Mini)': 'binance_dex_mini',
  'Binance (Futures)': 'binance_futures',
  'Binance US': 'binance_us',
  'BingX': 'bingx',
  'BingX (Futures)': 'bingx_futures',
  'BiONE': 'bione',
  'Birake': 'birake',
  'Bisq': 'bisq',
  'Biswap': 'biswap',
  'Bitc': 'bitc',
  'Bitazza': 'bitazza',
  'Bitbank': 'bitbank',
  'Zonda': 'bitbay',
  'BitBNS': 'bitbns',
  'BITFRONT': 'bitbox',
  'Bitbuy': 'bitbuy',
  'Bitci': 'bitci',
  'FMFW.io': 'bitcoin_com',
  'Bit.com': 'bit_com',
  'Bit.com (Futures)': 'bit_com_futures',
  'BITEXBOOK': 'bitexbook',
  'Bitexen': 'bitexen',
  'Bitexlive': 'bitexlive',
  'Bitfex': 'bitfex',
  'Bitfinex': 'bitfinex',
  'Bitfinex (Futures)': 'bitfinex_futures',
  'bitFlyer': 'bitflyer',
  'Bitflyer (Futures)': 'bitflyer_futures',
  'Bitforex': 'bitforex',
  'Bitforex (Futures)': 'bitforex_futures',
  'Bitget': 'bitget',
  'Bitget Futures': 'bitget_futures',
  'BitHash': 'bithash',
  'Bithumb': 'bithumb',
  'Bithumb (Futures)': 'bithumb_futures',
  'BitGlobal': 'bithumb_global',
  'Bitinka.com': 'bitinka',
  'BitKonan': 'bitkonan',
  'Bitkub': 'bitkub',
  'BitMart': 'bitmart',
  'Bitmart Futures': 'bitmart_futures',
  'AscendEX (BitMax)': 'bitmax',
  'AscendEX  (BitMax) (Futures)': 'bitmax_futures',
  'BitMEX (Derivative)': 'bitmex',
  'BitMEX': 'bitmex_spot',
  'Bitoffer': 'bitoffer',
  'BitOnBay': 'bitonbay',
  'BitoPro': 'bitopro',
  'Bitpanda Pro': 'bitpanda',
  'Bitrue': 'bitrue',
  'Bitrue (Futures)': 'bitrue_futures',
  'Bitso': 'bitso',
  'Bitstamp': 'bitstamp',
  'Bitsten': 'bitsten',
  'BitStorage': 'bitstorage',
  'Bittrex': 'bittrex',
  'Bitubu Exchange': 'bitubu',
  'Bitvavo': 'bitvavo',
  'BitZ (Futures)': 'bitz_futures',
  'BKEX': 'bkex',
  'Blockchain.com': 'blockchain_com',
  'BossSwap': 'bossswap',
  'BTC-Alpha': 'btc_alpha',
  'BTCBOX': 'btcbox',
  'BTCC': 'btcc',
  'BTCC Futures': 'btcc_futures',
  'BTCEX': 'btcex',
  'Btc Exchange': 'btc_exchange',
  'BTCEX (Futures)': 'btcex_futures',
  'BTCMarkets': 'btcmarkets',
  'BTCMEX': 'btcmex',
  'BTCSquare': 'btcsquare',
  'BTC Trade UA': 'btc_trade_ua',
  'BtcTurk PRO': 'btcturk',
  'BTSE': 'btse',
  'BTSE (Futures)': 'btse_futures',
  'Bullish': 'bullish_com',
  'BuyUcoin': 'buyucoin',
  'BW.com': 'bw',
  'Bybit': 'bybit',
  'Bybit (Spot)': 'bybit_spot',
  'Capricorn': 'capricorn',
  'Catex': 'catex',
  'CBX': 'cbx',
  'C-CEX': 'ccex',
  'CEX.IO': 'cex',
  'ChainEX': 'chainex',
  'Changelly PRO': 'changelly',
  'CherrySwap': 'cherryswap',
  'Chiliz': 'chiliz',
  'CITEX': 'citex',
  'Claimswap': 'claimswap',
  'Clipper (Ethereum)': 'clipper_ethereum',
  'Clipper (Moonbeam)': 'clipper_moonbeam',
  'Clipper (Optimism)': 'clipper_optimism',
  'Clipper (Polygon)': 'clipper_polygon',
  'CME Group': 'cme_futures',
  'CoinBene': 'coinbene',
  'Coincheck': 'coincheck',
  'CoinDCX': 'coindcx',
  'Coindeal': 'coindeal',
  'CoinEgg': 'coin_egg',
  'CoinEx': 'coinex',
  'CoinEx (Futures)': 'coinex_futures',
  'Coinfalcon': 'coinfalcon',
  'Coinfield': 'coinfield',
  'CoinFLEX': 'coinflex',
  'CoinFLEX (Futures)': 'coinflex_futures',
  'Coingi': 'coingi',
  'CoinJar Exchange': 'coinjar',
  'Coinlist': 'coinlist',
  'CoinMargin': 'coinmargin',
  'Coinmetro': 'coin_metro',
  'Coinone': 'coinone',
  'Coinsbit': 'coinsbit',
  'Coinstore': 'coinstore',
  'CoinTiger': 'cointiger',
  'CoinTiger (Futures)': 'cointiger_futures',
  'Coinzoom': 'coinzoom',
  'ComethSwap': 'comethswap',
  'Concave': 'concave',
  'C-Patex': 'c_patex',
  'Crema Finance': 'crema_finance',
  'Crescent': 'crescent',
  'CREX': 'crex',
  'Crodex': 'crodex',
  'Cronaswap': 'cronaswap',
  'Cronus Finance': 'cronus_finance',
  'Crypto.com Exchange': 'crypto_com',
  'Crypto.com Exchange (Futures)': 'crypto_com_futures',
  'Cryptology': 'cryptology',
  'C-Trade': 'c_trade',
  'Currency.com': 'currency',
  'Curve (Arbitrum)': 'curve_arbitrum',
  'Curve (Avalanche)': 'curve_avalanche',
  'Curve (Ethereum)': 'curve_ethereum',
  'Curve (Fantom)': 'curve_fantom',
  'Curve (Optimism)': 'curve_optimism',
  'Curve (Polygon)': 'curve_polygon',
  'Curve (Xdai)': 'curve_xdai',
  'Dark KnightSwap': 'darkknight',
  'Dcoin': 'dcoin',
  'Decoin': 'decoin',
  'DeFiChain DEX': 'defichain',
  'Defi Kingdoms': 'defi_kingdoms',
  'Defi Kingdoms (Crystalvale)': 'defi_kingdoms_crystalvale',
  'DefiPlaza': 'defi_plaza',
  'DeFi Swap': 'defi_swap',
  'Delta Exchange (Futures)': 'delta_futures',
  'Delta Exchange': 'delta_spot',
  'Demex': 'dem_exchange',
  'Deribit': 'deribit',
  'Rhino.fi': 'deversifi',
  'Dexalot': 'dexalot',
  'Dex-Trade': 'dextrade',
  'DFX': 'dfx',
  'DFX (Polygon)': 'dfx_polygon',
  'Dfyn': 'dfyn',
  'Diffusion Finance': 'diffusion',
  'Digifinex': 'digifinex',
  'KyberSwap Classic (Ethereum)': 'dmm',
  'KyberSwap Classic (Avalanche)': 'dmm_avalanche',
  'KyberSwap Classic (BSC)': 'dmm_bsc',
  'KyberSwap Classic (Fantom)': 'dmm_fantom',
  'KyberSwap Classic (Polygon)': 'dmm_polygon',
  'DODO': 'dodo',
  'Dodo (Arbitrum)': 'dodo_arbitrum',
  'Dodo (BSC)': 'dodo_bsc',
  'Dodo (Polygon)': 'dodo_polygon',
  'Dogeshrek': 'dogeshrek',
  'DogeSwap': 'dogeswap',
  'DOOAR (BSC)': 'dooar_bsc',
  'DOOAR (Ethereum)': 'dooar_ethereum',
  'BTX': 'dove_wallet',
  'Drift Protocol': 'drift_protocol',
  'DuckyDeFi': 'duckydefi',
  'DueDEX': 'duedex',
  'dYdX': 'dydx',
  'dYdX Perpetual': 'dydx_perpetual',
  'Dystopia': 'dystopia',
  'Elk Finance (Avalanche)': 'elk_finance_avax',
  'Elk Finance (BSC)': 'elk_finance_bsc',
  'Elk Finance (Ethereum)': 'elk_finance_ethereum',
  'Elk Finance (Polygon)': 'elk_finance_polygon',
  'Elk Finance (Telos)': 'elk_finance_telos',
  'Emirex': 'emirex',
  'EmpireDEX (Cronos)': 'empiredex',
  'EmpireDEX (BSC)': 'empiredex_bsc',
  'Energiswap': 'energiswap',
  'EQONEX': 'equos',
  'EQONEX (Perpetual)': 'equos_perpetual',
  'eToro': 'etorox',
  'EvmoSwap': 'evmoswap',
  'Excalibur': 'excalibur',
  'ExMarkets': 'exmarkets',
  'EXMO': 'exmo',
  'FatBTC': 'fatbtc',
  'FinexBox': 'finexbox',
  'Firebird Finance (Polygon)': 'firebird_finance_polygon',
  'FlatQube': 'flatqube',
  'Flybit': 'flybit',
  'swap': 'four_swap',
  'Foxbit': 'foxbit',
  'Fraxswap (Ethereum)': 'fraxswap_ethereum',
  'Freiexchange': 'freiexchange',
  'FTX (Derivatives)': 'ftx',
  'FTX': 'ftx_spot',
  'FTX TR': 'ftx_tr',
  'FTX.US': 'ftx_us',
  'Futureswap': 'futureswap',
  'FuzzSwap': 'fuzz_finance',
  'Gate.io': 'gate',
  'Gate.io (Futures)': 'gate_futures',
  'GDAC': 'gdac',
  'Coinbase Exchange': 'gdax',
  'Gemini': 'gemini',
  'Glide Finance': 'glide_finance',
  'GMO Japan': 'gmo_japan',
  'GMO Japan (Futures)': 'gmo_japan_futures',
  'GokuMarket': 'goku',
  'GoPax': 'gopax',
  'Graviex': 'graviex',
  'Greenhouse': 'greenhouse_dex',
  'HakuSwap': 'hakuswap',
  'Hanbitco': 'hanbitco',
  'BHEX (Futures)': 'hbtc_futures',
  'Hermes Protocol': 'hermes_protocol',
  'HitBTC': 'hitbtc',
  'Honeyswap': 'honeyswap',
  'Honeyswap (Polygon)': 'honeyswap_polygon',
  'Hoo.com': 'hoo',
  'Hopex': 'hopex',
  'Huckleberry': 'huckleberry',
  'Huobi Global': 'huobi',
  'Huobi Futures': 'huobi_dm',
  'Huobi Japan': 'huobi_japan',
  'Huobi Korea': 'huobi_korea',
  'Idex': 'idex',
  'Impossible Finance': 'impossible_finance',
  'Independent Reserve': 'independent_reserve',
  'Indodax': 'indodax',
  'Injective Pro': 'injective',
  'Injective Pro (Futures)': 'injective_futures',
  'itBit': 'itbit',
  'JetSwap': 'jetswap',
  'Binance JEX (Futures)': 'jex_futures',
  'Jswap': 'jswap',
  'Julswap': 'julswap',
  'Jupiter': 'jupiter',
  'Kaidex': 'kaidex',
  'Kanga': 'kanga',
  'Karura Swap': 'karura_swap',
  'Katana': 'katana',
  'Kava Swap': 'kava',
  'KickEX': 'kickex',
  'KnightSwap': 'knightswap',
  'Koinbazar': 'koinbazar',
  'Korbit': 'korbit',
  'Kraken': 'kraken',
  'Kraken (Futures)': 'kraken_futures',
  'KuCoin': 'kucoin',
  'Kujira Fin': 'kujira',
  'KuCoin Futures': 'kumex',
  'Kuna Exchange': 'kuna',
  'Kuswap': 'kuswap',
  'LATOKEN': 'latoken',
  'LBank': 'lbank',
  'LCX Exchange': 'lcx',
  'LeonicornSwap': 'leonicornswap',
  'Levinswap (xDai)': 'levinswap_xdai',
  'LIF': 'lif',
  'Liquid Perpetuals': 'liquid_derivatives',
  'LocalTrade': 'localtrade',
  'Loop Markets': 'loop',
  'Loopring': 'loopring',
  'Loopring AMM': 'loopring_amm',
  'Luaswap': 'luaswap',
  'Luno': 'luno',
  'Lydia Finance': 'lydia_finance',
  'Lykke': 'lykke',
  'Maiar': 'maiar',
  'Makiswap': 'makiswap',
  'Mango Markets (Derivatives)': 'mango_markets_derivatives',
  'Mango Markets (Spot)': 'mango_markets_spot',
  'Mars Ecosystem': 'mars_ecosystem',
  'Max Maicoin': 'max_maicoin',
  'MCDEX (Arbitrum)': 'mcdex',
  'MCDEX (BSC)': 'mcdex_bsc',
  'Mdex': 'mdex',
  'Mdex BSC': 'mdex_bsc',
  'Mercado Bitcoin': 'mercado_bitcoin',
  'Mercatox': 'mercatox',
  'MilkySwap': 'milkyswap-milkada',
  'Mimo': 'mimo',
  'Mistswap': 'mistswap_smart_bitcoin_cash',
  'MMFinance (Cronos)': 'mm_finance',
  'MMFinance (Polygon)': 'mmfinance_polygon',
  'MojitoSwap': 'mojitoswap',
  'Morpheus Swap': 'morpheus_swap',
  'Muesliswap (Milkada)': 'muesliswap-milkada',
  'MEXC Global': 'mxc',
  'MEXC Global (Futures)': 'mxc_futures',
  'MCS': 'mycoinstory',
  'NachoSwap': 'nachoswap',
  'Namebase': 'namebase',
  'Nami.Exchange': 'nami_exchange',
  'Narkasa': 'narkasa',
  'Nash': 'nash',
  'NearPAD': 'nearpad',
  'Negociecoins': 'negociecoins',
  'Netswap': 'netswap',
  'Newdex': 'newdex',
  'Nexus Mutual': 'nexus_mutual',
  'NiceHash': 'nice_hash',
  'Nominex': 'nominex',
  'Nomiswap': 'nomiswap',
  'NovaDAX': 'novadax',
  'OasisDEX': 'oasis_trade',
  'OccamX': 'occamx',
  'Oceanex': 'oceanex',
  'Okcoin': 'okcoin',
  'OKX': 'okex',
  'OKX (Futures)': 'okex_swap',
  'Omgfin': 'omgfin',
  'OmniDex': 'omnidex',
  'inch Liquidity Protocol': 'one_inch_liquidity_protocol',
  'inch Liquidity Protocol (BSC)': 'one_inch_liquidity_protocol_bsc',
  'Oolongswap': 'oolongswap',
  'OpenLeverage': 'openleverage',
  'OpenOcean': 'openocean_finance',
  'OpenSwap': 'openswap',
  'Orca': 'orca',
  'Orderbook.io': 'orderbook',
  'Osmosis': 'osmosis',
  'Ovex': 'ovex',
  'PPBB': 'ppbb',
  'Paintswap': 'paintswap',
  'PancakeSwap (v)': 'pancakeswap_new',
  'Pangolin': 'pangolin',
  'Paribu': 'paribu',
  'Paritex': 'paritex',
  'Paymium': 'paymium',
  'Pegasys': 'pegasys',
  'Perpetual Protocol': 'perpetual_protocol',
  'Phemex': 'phemex',
  'Phemex (Futures)': 'phemex_futures',
  'PhotonSwap (Cronos)': 'photonswap',
  'PhotonSwap (Kava)': 'photonswap_kava',
  'PinkSwap': 'pinkswap',
  'Platypus Finance': 'platypus_finance',
  'PolkaEx (Shiden)': 'polkaex_shiden',
  'Polkaswap': 'polkaswap',
  'Poloniex': 'poloniex',
  'Poloniex Futures': 'poloniex_futures',
  'Polycat Finance': 'polycat_finance',
  'PolyDEX': 'polydex',
  'PolyZap': 'polyzap',
  'Powertrade': 'powertrade',
  'Prime XBT': 'prime_xbt',
  'Prism Protocol': 'prism',
  'ProBit Global': 'probit',
  'Probit (Korea)': 'probit_kr',
  'ProtoFi': 'protofi',
  'PuddingSwap': 'puddingswap',
  'qTrade': 'qtrade',
  'Quickswap': 'quickswap',
  'Quipuswap': 'quipuswap',
  'Liquid': 'quoine',
  'RadioShack (Avalanche)': 'radioshack_avalanche',
  'RadioShack (BSC)': 'radioshack_bsc',
  'RadioShack (Ethereum)': 'radioshack_ethereum',
  'RadioShack (Polygon)': 'radioshack_polygon_pos',
  'Raydium': 'raydium',
  'Ref Finance': 'ref_finance',
  'Resfinex': 'resfinex',
  'Saber': 'saber',
  'SafeTrade': 'safe_trade',
  'SakeSwap': 'sakeswap',
  'Saros Finance': 'saros',
  'SecondBTC': 'secondbtc',
  'SecretSwap': 'secretswap',
  'Serum DEX': 'serum_dex',
  'SharkSwap': 'sharkswap',
  'Shibaswap': 'shibaswap',
  'Siennaswap': 'siennaswap',
  'Sifchain': 'sifchain',
  'SINEGY': 'sinegy',
  'Solarbeam': 'solarbeam',
  'Solarflare': 'solarflare',
  'Solidly': 'solidly',
  'Soulswap': 'soulswap',
  'SouthXchange': 'south_xchange',
  'Spartan Protocol': 'spartan_protocol',
  'Sphynx (Brise)': 'sphynx_brise',
  'Sphynx Swap (BSC)': 'sphynx_swap',
  'SpiritSwap': 'spiritswap',
  'SpiritSwap (V)': 'spiritswap_v',
  'SpookySwap': 'spookyswap',
  'StakeCube Exchange': 'stake_cube',
  'StellarTerm': 'stellar_term',
  'StellaSwap': 'stellaswap',
  'Step Finance': 'step_finance',
  'STEX': 'stocks_exchange',
  'Stormgain': 'stormgain',
  'Stormgain Futures': 'stormgain_futures',
  'SUN.io': 'sunswap_v',
  'Sushiswap': 'sushiswap',
  'Sushiswap (Arbitrum One)': 'sushiswap_arbitrum',
  'Sushiswap (Avalanche)': 'sushiswap_avalanche',
  'Sushiswap (BSC)': 'sushiswap_bsc',
  'Sushiswap Celo': 'sushiswap_celo',
  'Sushiswap (Fantom)': 'sushiswap_fantom',
  'Sushiswap (Harmony)': 'sushiswap_harmony',
  'Sushiswap (Polygon POS)': 'sushiswap_polygon_pos',
  'Sushiswap (xDai)': 'sushiswap_xdai',
  'Swappi': 'swappi',
  'Swapr (Arbitrum)': 'swapr_arbitrum',
  'Swapr (Ethereum)': 'swapr_ethereum',
  'Swapr (Xdai)': 'swapr_xdai',
  'Swop.Fi': 'swop_fi',
  'SWYCH': 'swych',
  'Kwenta': 'synthetix',
  'TangoSwap': 'tangoswap',
  'Satang Pro': 'tdax',
  'TempleDAO': 'templedao',
  'Tenderswap': 'tenderswap',
  'Terraswap': 'terraswap',
  'Tethys Finance': 'tethys',
  'Tetuswap': 'tetuswap',
  'Terraformer': 'tfm',
  'TheRockTrading': 'therocktrading',
  'THORSwap': 'thorswap',
  'Thorus': 'thorus',
  'Tidex': 'tidex',
  'Tokenize': 'tokenize',
  'Tokenlon': 'tokenlon',
  'Tokenomy': 'tokenomy',
  'TokenSets': 'token_sets',
  'TokoCrypto': 'toko_crypto',
  'TOKOK': 'tokok',
  'Tokpie': 'tokpie',
  'Tomb Swap (Fantom)': 'tomb_swap_fantom',
  'TradeOgre': 'trade_ogre',
  'Trader Joe': 'traderjoe',
  'Tranquil Finance': 'tranquil_finance',
  'Trisolaris': 'trisolaris',
  'Tropical Finance': 'tropical_finance',
  'Txbit': 'txbit',
  'Ubeswap': 'ubeswap',
  'Unicly': 'unicly',
  'Uniswap (v)': 'uniswap',
  'Uniswap (Optimism)': 'uniswap_optimism',
  'Uniswap (Polygon)': 'uniswap_polygon',
  'Uniswap (v)': 'uniswap_v',
  'Uniswap (Arbitrum One)': 'uniswap_v_arbitrum',
  'Unnamed': 'unnamed',
  'Upbit': 'upbit',
  'Upbit Indonesia ': 'upbit_indonesia',
  'vSwap BSC': 'value_liquid_bsc',
  'Velic': 'velic',
  'Velodrome Finance': 'velodrome',
  'Vindax': 'vindax',
  'ViperSwap': 'viperswap',
  'ViteX': 'vitex',
  'Voltage Finance': 'voltage_finance',
  'Voltswap (Meter)': 'voltswap_meter',
  'Voltswap (Theta)': 'voltswap_theta',
  'VVS Finance': 'vvs',
  'WagyuSwap': 'wagyuswap',
  'Wannaswap': 'wannaswap',
  'WanSwap': 'wanswap',
  'WaultSwap Polygon': 'waultswap_polygon',
  'Waves.Exchange': 'waves',
  'WazirX': 'wazirx',
  'WhiteBIT': 'whitebit',
  'Wigoswap': 'wigoswap',
  'WOOFi': 'woofi',
  'WOO Network (Futures)': 'woo_network_futures',
  'WOO Network': 'wootrade',
  'XT.COM': 'xt',
  'YoBit': 'yobit',
  'Yoshi.exchange (BSC)': 'yoshi_exchange_bsc',
  'Yoshi.exchange (Fantom)': 'yoshi_exchange_ftm',
  'Yunex.io': 'yunex',
  'Zaif': 'zaif',
  'Zappy': 'zappy',
  'ZBG': 'zbg',
  'ZBG Futures': 'zbg_futures',
  'ZBX': 'zbx',
  'Zebitex': 'zebitex',
  'ZebPay': 'zebpay',
  'Zenlink (Astar)': 'zenlink_astar',
  'Zenlink (Moonbeam)': 'zenlink_moonbeam',
  'Zenlink (Moonriver)': 'zenlink_moonriver',
  'x Protocol': 'zero_ex',
  'ZigZag': 'zigzag',
  'ZilSwap': 'zilswap',
  'Zipmex': 'zipmex',
  'ZipSwap': 'zipswap',
}

export const exchangeIcons = {
  binance: 'https://assets.coingecko.com/markets/images//small/binance.jpg?',
  gdax: 'https://assets.coingecko.com/markets/images//small/Coinbase_Coin_Primary.png?',
  ftx_spot: 'https://assets.coingecko.com/markets/images//small/F.png?',
  okex: 'https://assets.coingecko.com/markets/images//small/WeChat_Image_.png?',
  gate: 'https://assets.coingecko.com/markets/images//small/gate_io_logo.jpg?',
  kucoin: 'https://assets.coingecko.com/markets/images//small/kucoin.png?',
  huobi: 'https://assets.coingecko.com/markets/images//small/Huobi.?',
  kraken: 'https://assets.coingecko.com/markets/images//small/kraken.jpg?',
  crypto_com: 'https://assets.coingecko.com/markets/images//small/Crypto.jpg?',
  bitfinex: 'https://assets.coingecko.com/markets/images//small/BItfinex.png?',
  binance_us: 'https://assets.coingecko.com/markets/images//small/Binance.png?',
  bybit_spot: 'https://assets.coingecko.com/markets/images//small/bybit_spot.png?',
  ftx_us: 'https://assets.coingecko.com/markets/images//small/FTX-US.jpg?',
  gemini: 'https://assets.coingecko.com/markets/images//small/gemini.png?',
  mxc: 'https://assets.coingecko.com/markets/images//small/WeChat_Image_.png?',
  bittrex: 'https://assets.coingecko.com/markets/images//small/BG-color-x_icon.png?',
  bitmex_spot: 'https://assets.coingecko.com/markets/images//small/bitmex.jpeg?',
  xt: 'https://assets.coingecko.com/markets/images//small/logox.png?',
  bitmart: 'https://assets.coingecko.com/markets/images//small/Bitmart.png?',
  bitcoin_com: 'https://assets.coingecko.com/markets/images//small/fmfw.png?',
  aax: 'https://assets.coingecko.com/markets/images//small/aax_app_logo.png?',
  bitrue: 'https://assets.coingecko.com/markets/images//small/unnamed_%%.png?',
  ppbb: 'https://assets.coingecko.com/markets/images//small/ppbb.jpg?',
  lbank: 'https://assets.coingecko.com/markets/images//small/LBank%E%C%%E%A%.png?',
  ftx_tr: 'https://assets.coingecko.com/markets/images//small/ftxtr.png?',
  whitebit: 'https://assets.coingecko.com/markets/images//small/wb__avatar-.png?',
  phemex: 'https://assets.coingecko.com/markets/images//small/Phemex_logo_.png?',
  bullish_com: 'https://assets.coingecko.com/markets/images//small/bullish_com.png?',
  bitget: 'https://assets.coingecko.com/markets/images//small/Bitget_new_logo_.png?',
  dextrade: 'https://assets.coingecko.com/markets/images//small/Dex-Trade_logo_new.png?',
  btse: 'https://assets.coingecko.com/markets/images//small/BTSE.jpg?',
  wootrade: 'https://assets.coingecko.com/markets/images//small/wootrade.jpg?',
  coinstore: 'https://assets.coingecko.com/markets/images//small/coinstore.jpeg?',
  bitstamp: 'https://assets.coingecko.com/markets/images//small/bitstamp.jpg?',
  btcturk: 'https://assets.coingecko.com/markets/images//small/BTCTurk-exchange.jpg?',
  bitmax: 'https://assets.coingecko.com/markets/images//small/%E%E%F%E%%B.png?',
  exmo: 'https://assets.coingecko.com/markets/images//small/new_logo-.jpg?',
  okcoin: 'https://assets.coingecko.com/markets/images//small/okcoin_Logomark_SatoshiBlack.png?',
  kickex: 'https://assets.coingecko.com/markets/images//small/KickEX_logo.png?',
  blockchain_com: 'https://assets.coingecko.com/markets/images//small/unnamedddd.png?',
  coinex: 'https://assets.coingecko.com/markets/images//small/coinex.jpg?',
  bitbank: 'https://assets.coingecko.com/markets/images//small/bitbank.jpg?',
  tokenize: 'https://assets.coingecko.com/markets/images//small/tokenize-exchange.png?',
  luno: 'https://assets.coingecko.com/markets/images//small/luno.jpg?',
  nominex: 'https://assets.coingecko.com/markets/images//small/logo-x.png?',
  bitpanda: 'https://assets.coingecko.com/markets/images//small/appicon-ios-pro.png?',
  bitopro: 'https://assets.coingecko.com/markets/images//small/bitopro_coingecko_x_%%.png?',
  kuna: 'https://assets.coingecko.com/markets/images//small/kuna_exchange.png?',
  nice_hash: 'https://assets.coingecko.com/markets/images//small/logo_small_light.png?',
  lcx: 'https://assets.coingecko.com/markets/images//small/LCX.jpg?',
  digifinex: 'https://assets.coingecko.com/markets/images//small/DF_logo.png?',
  bkex: 'https://assets.coingecko.com/markets/images//small/New_BKEX_logo.png?',
  upbit: 'https://assets.coingecko.com/markets/images//small/upbit.png?',
  coinsbit: 'https://assets.coingecko.com/markets/images//small/Coinsbit.png?',
  bigone: 'https://assets.coingecko.com/markets/images//small/qcFFufEY_x.jpg?',
  btcex: 'https://assets.coingecko.com/markets/images//small/CtiQdwL_x.jpg?',
  bingx: 'https://assets.coingecko.com/markets/images//small/YtFwQwJr_x.jpg?',
  biconomy: 'https://assets.coingecko.com/markets/images//small/biconomy-cex.png?',
  currency: 'https://assets.coingecko.com/markets/images//small/Currency.com_x.png?',
  latoken: 'https://assets.coingecko.com/markets/images//small/LA_token.png?',
  bibox: 'https://assets.coingecko.com/markets/images//small/bibox.jpg?',
  decoin: 'https://assets.coingecko.com/markets/images//small/decoin.jpg?',
  tidex: 'https://assets.coingecko.com/markets/images//small/favicon.png?',
  paribu: 'https://assets.coingecko.com/markets/images//small/paribu.jpg?',
  coinone: 'https://assets.coingecko.com/markets/images//small/coinone_circle_x.png?',
  bit_com: 'https://assets.coingecko.com/markets/images//small/IMAGE_--___.jpg?',
  catex: 'https://assets.coingecko.com/markets/images//small/catex.png?',
  exmarkets: 'https://assets.coingecko.com/markets/images//small/___n.jpg?',
  bitflyer: 'https://assets.coingecko.com/markets/images//small/bitFlyer-logo.png?',
  poloniex: 'https://assets.coingecko.com/markets/images//small/poloniex-.png?',
  bitkub: 'https://assets.coingecko.com/markets/images//small/bitkub.png?',
  cryptology: 'https://assets.coingecko.com/markets/images//small/cryptology.png?',
  tokpie: 'https://assets.coingecko.com/markets/images//small/logo_circle_x.png?',
  bitso: 'https://assets.coingecko.com/markets/images//small/Bitso-icon-dark.png?',
  max_maicoin: 'https://assets.coingecko.com/markets/images//small/max.jpg?',
  bbx: 'https://assets.coingecko.com/markets/images//small/bbx.jpg?',
  independent_reserve: 'https://assets.coingecko.com/markets/images//small/x_VJquo_x.png?',
  bitazza: 'https://assets.coingecko.com/markets/images//small/btzlogox_darkgreen.png?',
  cex: 'https://assets.coingecko.com/markets/images//small/main-icon.png?',
  etorox: 'https://assets.coingecko.com/markets/images//small/eToro-logo-x.png?',
  mercado_bitcoin: 'https://assets.coingecko.com/markets/images//small/logo_MB_hexagono.png?',
  wazirx: 'https://assets.coingecko.com/markets/images//small/wazirx.jpg?',
  coinlist: 'https://assets.coingecko.com/markets/images//small/CoinList.png?',
  coin_metro: 'https://assets.coingecko.com/markets/images//small/Coinmetro_Exchange_Logo_%%.png?',
  zaif: 'https://assets.coingecko.com/markets/images//small/zaif.png?',
  flybit: 'https://assets.coingecko.com/markets/images//small/flybit_logo_%EA%B%%EB%A%C%ED%%.png?',
  delta_spot: 'https://assets.coingecko.com/markets/images//small/delta_spot.jpg?',
  hitbtc: 'https://assets.coingecko.com/markets/images//small/hitbtc.png?',
  uniswap: 'https://assets.coingecko.com/markets/images//small/uniswap-v.png?',
  bithumb: 'https://assets.coingecko.com/markets/images//small/bithumb_BI.png?',
  bitforex: 'https://assets.coingecko.com/markets/images//small/BitForex-Logo.png?',
  pancakeswap_new: 'https://assets.coingecko.com/markets/images//small/pancakeswap.jpeg?',
  probit: 'https://assets.coingecko.com/markets/images//small/probit.png?',
  bitexen: 'https://assets.coingecko.com/markets/images//small/Bitexen_Logo_Short.png?',
  bitvavo: 'https://assets.coingecko.com/markets/images//small/bitvavo-mark-square-black.png?',
  uniswap_v: 'https://assets.coingecko.com/markets/images//small/x_Black-.png?',
  changelly: 'https://assets.coingecko.com/markets/images//small/pro_logo_cmc.png?',
  oceanex: 'https://assets.coingecko.com/markets/images//small/Oceanex.png?',
  uniswap_optimism: 'https://assets.coingecko.com/markets/images//small/uniswap-v.png?',
  coincheck: 'https://assets.coingecko.com/markets/images//small/Coincheck.jpg?',
}

export const coindIds = {
  btc: 'bitcoin',
  eth: 'ethereum',
  usdt: 'tether',
  usdc: 'usd-coin',
  bnb: 'binancecoin',
  xrp: 'ripple',
  busd: 'binance-usd',
  ada: 'cardano',
  sol: 'solana',
  doge: 'dogecoin',
  dot: 'polkadot',
  shib: 'shiba-inu',
  steth: 'staked-ether',
  avax: 'avalanche-',
  matic: 'matic-network',
  dai: 'dai',
  trx: 'tron',
  wbtc: 'wrapped-bitcoin',
  etc: 'ethereum-classic',
  okb: 'okb',
  leo: 'leo-token',
  ltc: 'litecoin',
  ftt: 'ftx-token',
  near: 'near',
  link: 'chainlink',
  cro: 'crypto-com-chain',
  uni: 'uniswap',
  atom: 'cosmos',
  xlm: 'stellar',
  xmr: 'monero',
  flow: 'flow',
  bch: 'bitcoin-cash',
  algo: 'algorand',
  fil: 'filecoin',
  vet: 'vechain',
  ape: 'apecoin',
  icp: 'internet-computer',
  xcn: 'chain-',
  mana: 'decentraland',
  sand: 'the-sandbox',
  hbar: 'hedera-hashgraph',
  xtz: 'tezos',
  axs: 'axie-infinity',
  qnt: 'quant-network',
  eos: 'eos',
  frax: 'frax',
  theta: 'theta-token',
  aave: 'aave',
  ldo: 'lido-dao',
  egld: 'elrond-erd-',
}

